/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fit.geotrip;

import java.awt.Frame;
import java.io.File;
import java.io.FilenameFilter;
import java.util.LinkedList;
import java.util.List;
import java.util.prefs.Preferences;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author jan
 */
public class SettingsDialog extends javax.swing.JDialog {

    Frame parent;
    GeoTrip geoTrip;
    
    public SettingsDialog(Frame parent, boolean modal, GeoTrip geoTrip) {
        super(parent, modal);
        this.parent = parent;
        this.geoTrip = geoTrip;
        
        initComponents();

        this.setLocation(parent.getLocation().x + parent.getSize().width / 2 - this.getSize().width / 2, 
                parent.getLocation().y + parent.getSize().height / 2 - this.getSize().height / 2);

        findMaps();
    }

    private void findMaps() {
        comboMap.removeAllItems();
        
        File dir = new File("data/maps");
         
        List<String> tmp = new LinkedList<>();
        
        File[] mapArray = dir.listFiles(new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.toLowerCase().endsWith(".map");
            }
        }); 
        
        File[] osmArray = dir.listFiles(new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.toLowerCase().endsWith(".osm.pbf");
            }
        });
        
        for (File f : mapArray) 
            tmp.add(f.getName().split(Pattern.quote("."))[0]);
        
        for (File f : osmArray) {
            String name = f.getName().split(Pattern.quote("."))[0];
            if (tmp.contains(name)) 
                comboMap.addItem(name);
        }
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMap = new javax.swing.JPanel();
        comboMap = new javax.swing.JComboBox();
        panelLanguage = new javax.swing.JPanel();
        comboLanguage = new javax.swing.JComboBox();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nastavení");
        setResizable(false);

        panelMap.setBorder(javax.swing.BorderFactory.createTitledBorder("Mapa"));

        javax.swing.GroupLayout panelMapLayout = new javax.swing.GroupLayout(panelMap);
        panelMap.setLayout(panelMapLayout);
        panelMapLayout.setHorizontalGroup(
            panelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboMap, 0, 200, Short.MAX_VALUE)
        );
        panelMapLayout.setVerticalGroup(
            panelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelLanguage.setBorder(javax.swing.BorderFactory.createTitledBorder("Jazyk"));

        comboLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Čeština" }));

        javax.swing.GroupLayout panelLanguageLayout = new javax.swing.GroupLayout(panelLanguage);
        panelLanguage.setLayout(panelLanguageLayout);
        panelLanguageLayout.setHorizontalGroup(
            panelLanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboLanguage, 0, 200, Short.MAX_VALUE)
        );
        panelLanguageLayout.setVerticalGroup(
            panelLanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        buttonOk.setText("Ok");
        buttonOk.setPreferredSize(new java.awt.Dimension(80, 23));
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.setPreferredSize(new java.awt.Dimension(80, 23));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelLanguage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        Preferences prefs = Preferences.userNodeForPackage(GeoTrip.class);
        
        String language;
        switch(comboLanguage.getSelectedItem().toString()) {
            case "Čeština":
                language = "cs-CZ";
                break;
            default:
                language = "en-US";
                break;
        }
        if (!language.equals(prefs.get("language", null))) {
            prefs.put("language", language);
            JOptionPane.showMessageDialog(parent, "Jazyk bude zmenen pri dalsim spusteni aplikace.", "Zmena jazyka", JOptionPane.INFORMATION_MESSAGE);
        }
        
        String mapName = comboMap.getSelectedItem().toString();
        if (!mapName.equals(prefs.get("map", null))) {
            prefs.put("map", mapName);

            MapLoadDialog mapLoadDialog = new MapLoadDialog(parent, true, mapName);
            mapLoadDialog.setVisible(true);

            geoTrip.loadMap();
        }
        
        dispose();
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JComboBox comboLanguage;
    private javax.swing.JComboBox comboMap;
    private javax.swing.JPanel panelLanguage;
    private javax.swing.JPanel panelMap;
    // End of variables declaration//GEN-END:variables
}
